
services:
  nodejs-data-caching:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 4000:4000
    env_file:
      - ./envs/.env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    container_name: nodejs-data-caching-container

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - 16379:16379
    env_file:
      - ./envs/.env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - /redis/d–∞ta:/root/redis
      - /redis/data/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    container_name: redis-container

  postgres:
    image: postgres
    restart: always
    ports:
      - 15432:5432
    env_file:
      - ./envs/.env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    command: /bin/sh -c "./var/lib/postgresql/data/example_db_init.sh"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
    container_name: postgres-container
